### ISSUE TITLE
Editor: Title font anomalies

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-electron#1391]
There were 2 issues I noticed with titles in the react apps.

### Web
On https://app.simplenote.com/new I noticed the first sentence (title) had the same font size/weight as the body text:
<img width="748" alt="web_title_issue" src="https://user-images.githubusercontent.com/154014/59786904-ec0f9900-928d-11e9-82b7-2571585d4b8e.png">

### Electron
On the macOS Electron app, the title was a larger size, but not the correct weight. Additionally, only the first line was different instead of the entire first sentence:
<img width="795" alt="electron_title_issue" src="https://user-images.githubusercontent.com/154014/59786919-f03bb680-928d-11e9-9275-4ad9b889a467.png">

## Expected
I would expect the entire title to a higher weight typeface and slightly larger than the body text. In the editor, our design standards are currently this:

```css
h1{
  font-size: 22px;
  line-height: 1.36em;
  font-weight: 600;
  margin-bottom: 1.36em;
}
p{
  font-size: 19px;
  line-height: 1.5em;
  font-weight: 400;
  margin-bottom: 1.5em;
}
```

For comparison, a recent design mock with the same note above ☝️:
<img width="804" alt="screenshot-2019-06-19-at-16 43 48" src="https://user-images.githubusercontent.com/154014/59788195-d485df80-9290-11e9-8459-cc8d583a13cb.png">

/cc @SylvesterWilmott
